stages:
    - test
    - build

variables:
  MODCACHEDIR: $CI_PROJECT_DIR/.gomod
  VERSION: v0.0.5

.prep-go-env: &prep-go-env
  before_script:
    - mkdir -p $MODCACHEDIR $GOPATH/pkg
    - ln -s $MODCACHEDIR $GOPATH/pkg/mod
    - make mod

test:
  stage: test
  image: $CI_REGISTRY/sre/gudang/golang:2.1.0
  <<: *prep-go-env
  script:
    - go test -v
  cache:
    key: gomod
    paths:
    - $MODCACHEDIR

compile:
  image: $CI_REGISTRY/sre/gudang/golang:2.1.0
  stage: test
  script:
    - go build
  cache:
    key: gomod
    paths:
      - $MODCACHEDIR
  artifacts:
    expire_in: 1 days
    paths:
      - prometheus-aggregator

build-image:
  stage: build
  image: $CI_REGISTRY/sre/gudang/docker:1.0.0
  when: manual
  tags:
  - bare-metal
  dependencies:
  - compile
  script:
  - TAG=$CI_REGISTRY/bukalapak/prometheus-aggregator:$VERSION
  - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker build -t $TAG  .
  - docker push $TAG
