language: go

go:
  - 1.11.5

# Without this go11 modules will be disabled
env:
  - GO111MODULE=on

# Disable the old go get way travis will still automatically do if you use 'language: go'
install: true

script:
  - go build
  - go test -v -short .

  # Race tests are failing due to data race on switching sampleHasher.
  #- go test . -run Test_Race_ -race -count 100 -cpu 1,2,4,8,16
